/** Responsive WebP variants generated by scripts/optimize-images.mjs (-480 / -960 suffix). */
export function responsiveSrc(baseWebp: string, fullWidth = 800) {
  const stem = baseWebp.replace(/\.webp$/, "");
  return {
    src: baseWebp,
    srcSet: `${stem}-480.webp 480w, ${baseWebp} ${fullWidth}w`,
  };
}

export const GALLERY_SIZES =
  "(max-width: 768px) 100vw, (max-width: 1024px) 50vw, (max-width: 1280px) 33vw, 25vw";

export const CARD_SIZES =
  "(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 25vw";

export const EVENT_SIZES = "(max-width: 768px) 100vw, 33vw";

export const HERO = {
  src: "/all.webp",
  srcSet: "/all-960.webp 960w, /all.webp 1920w",
  sizes: "100vw",
} as const;
